# Generated by Django 5.2.14 on 2026-05-29 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0003_achievement_certification_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='resume_profiles/'),
        ),
    ]
