# Generated by Django 5.2.14 on 2026-05-30 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0004_resume_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='template',
            field=models.CharField(choices=[('template1', 'Template 1'), ('template2', 'Template 2'), ('template3', 'Template 3')], default='template1', max_length=100),
        ),
    ]
