# Generated by Django 5.2.14 on 2026-06-07 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0005_alter_resume_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='template',
            field=models.CharField(choices=[('template1', 'Template 1'), ('template2', 'Template 2'), ('template3', 'Template 3'), ('template4', 'Template 4'), ('template5', 'Template 5'), ('template6', 'Template 6'), ('template7', 'Template 7'), ('template8', 'Template 8'), ('template9', 'Template 9'), ('template10', 'Template 10'), ('template11', 'Template 11'), ('template12', 'Template 12'), ('template13', 'Template 13'), ('template14', 'Template 14'), ('template15', 'Template 15')], default='template1', max_length=100),
        ),
    ]
