# Generated by Django 5.2.14 on 2026-06-13 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0008_project_end_date_project_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='employment_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
