# Generated by Django 5.2.14 on 2026-06-13 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0009_experience_employment_type_experience_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='cgpa',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
